CREATE TABLE Departemnt(
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Name VARCHAR(25) UNIQUE NOT NULL,
    Location VARCHAR(33) NOT NULL
);

CREATE TABLE Job(
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Name VARCHAR(20) UNIQUE NOT NULL
);

CREATE TABLE Employee(
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Name VARCHAR(20) NOT NULL,
    JobId INT NOT NULL REFERENCES Job(Id),
    ManagerId INT FOREIGN KEY REFERENCES Employee(ID),
    HireDate DATETIME2 NOT NULL,
    Salary DECIMAL(7,2) NOT NULL,
    Commission DECIMAL(7,2),
    DepartmentId INT NOT NULL FOREIGN KEY REFERENCES Departemnt(Id)
);